create sequence USER_SERVER_SEQ start with 1 increment by 1;
create sequence USER_TEST_SEQ start with 1 increment by 1;
create table USER_SERVER (USER_ID number(19,0), id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
alter table USER_SERVER add constraint FK1ai2ifjm2d4hp9dsywubpyn2f foreign key (USER_ID) references USER_TEST;
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (USER_ID number(19,0), id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
alter table USER_SERVER add constraint FK1ai2ifjm2d4hp9dsywubpyn2f foreign key (USER_ID) references USER_TEST;
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (USER_ID number(19,0), id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
alter table USER_SERVER add constraint FK1ai2ifjm2d4hp9dsywubpyn2f foreign key (USER_ID) references USER_TEST;
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
create sequence USER_TEST_SEQ start with 1 increment by 1;
create table USER_SERVER (id number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence USER_TEST_SEQ start with 1 increment by 1;
create table USER_SERVER (id number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (id number(19,0) generated as identity, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), phone varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (password varchar2(255 char), userName varchar2(255 char) not null, primary key (userName));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, loginDetail_userName varchar2(255 char) unique, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
alter table USER_TEST add constraint FK9g83bqecrbryijsgrubx653ch foreign key (loginDetail_userName) references LOGIN_DETAIL;
create table LOGIN_DETAIL (password varchar2(255 char), userName varchar2(255 char) not null, primary key (userName));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (password varchar2(255 char), userName varchar2(255 char) not null, primary key (userName));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (password varchar2(255 char), userId varchar2(255 char) not null, primary key (userId));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (loginId varchar2(255 char) not null, password varchar2(255 char), primary key (loginId));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (loginId varchar2(255 char) not null, password varchar2(255 char), primary key (loginId));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (loginId varchar2(255 char) not null, password varchar2(255 char), primary key (loginId));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (id number(19,0) not null, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table USER_SERVER (id number(19,0) generated as identity, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAI varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAI varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 50;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAI varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAI varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAI varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DBTableSpaceDetail (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, TABLE_SPACE_NAME varchar2(255 char), tableSpaceName varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, SERVER_IP varchar2(255 char), TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, SERVER_IP varchar2(255 char), TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, SERVER_IP varchar2(255 char), TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, SERVER_IP varchar2(255 char), TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, SERVER_IP varchar2(255 char), TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence DB_TABLE_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence UNIX_SPACE_DETAIL_SEQ start with 1 increment by 1;
create sequence USER_SERVER_SEQ start with 1 increment by 1;
create table DB_TABLE_SPACE_DETAIL (PCT_USED float(53), SPACE_ALLOCATED float(53), SPACE_FREE float(53), SPACE_USED float(53), id number(19,0) not null, SERVER_IP varchar2(255 char), TABLE_SPACE_NAME varchar2(255 char), primary key (id));
create table LOGIN_DETAIL (id number(19,0) generated as identity, loginId varchar2(255 char), password varchar2(255 char), primary key (id));
create table UNIX_SPACE_DETAIL (id number(19,0) not null, FILE_SYSTEM varchar2(255 char), MOUNTED_ON varchar2(255 char), SERVER_IP varchar2(255 char), SPACE_AVAIL varchar2(255 char), SPACE_USED varchar2(255 char), TOTAL_SIZE varchar2(255 char), USED_PERC varchar2(255 char), primary key (id));
create table USER_SERVER (ID number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (ID));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), password varchar2(255 char), project varchar2(255 char), primary key (email));
