create sequence USER_SERVER_SEQ start with 1 increment by 1;
create sequence USER_TEST_SEQ start with 1 increment by 1;
create table USER_SERVER (USER_ID number(19,0), id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
alter table USER_SERVER add constraint FK1ai2ifjm2d4hp9dsywubpyn2f foreign key (USER_ID) references USER_TEST;
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (USER_ID number(19,0), id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
alter table USER_SERVER add constraint FK1ai2ifjm2d4hp9dsywubpyn2f foreign key (USER_ID) references USER_TEST;
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (USER_ID number(19,0), id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
alter table USER_SERVER add constraint FK1ai2ifjm2d4hp9dsywubpyn2f foreign key (USER_ID) references USER_TEST;
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
create sequence USER_SERVER_SEQ start with 1 increment by 50;
create sequence USER_TEST_SEQ start with 1 increment by 50;
create table USER_SERVER (id number(19,0) not null, serverIp varchar2(255 char), serverPassword varchar2(255 char), serverUserName varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), id number(19,0) not null, email varchar2(255 char), name varchar2(255 char), project varchar2(255 char), primary key (id));
create sequence USER_TEST_SEQ start with 1 increment by 1;
create table USER_SERVER (id number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create sequence USER_TEST_SEQ start with 1 increment by 1;
create table USER_SERVER (id number(19,0) not null, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (id number(19,0) generated as identity, SERVER_IP varchar2(255 char), SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (id));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), phone varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
create table USER_SERVER (SERVER_IP varchar2(255 char) not null, SERVER_PASSWORD varchar2(255 char), SERVER_USER_NAME varchar2(255 char), primary key (SERVER_IP));
create table USER_TEST (status number(10,0), email varchar2(255 char) not null, name varchar2(255 char), project varchar2(255 char), primary key (email));
